### PR TITLE
DAOS-15162 libfabric: update to 1.22.0

### PR DESCRIPTION
**Pull request by soumagne**
Drop prov/verbs patch merged upstream

Update libfabric1.symbols for debian build

Update packaging

### CODE REVIEW

**Comment by soumagne** [comment]
2.6 build completed without issues / master build failed because of https://daosio.atlassian.net/browse/DAOS-16732.

**Comment by soumagne** [comment]
@mchaarawi just a heads-up that I will need that PR to be merged relatively soon so that it gets into 2.6.2.

**Comment by mchaarawi** [comment]
> @mchaarawi just a heads-up that I will need that PR to be merged relatively soon so that it gets into 2.6.2.

it would help if the PR is passing ;-)

**Comment by soumagne** [comment]
it is passing 2.6, master's CI is broken...

**Comment by soumagne** [comment]
Created https://github.com/daos-stack/daos/pull/15401, we'll follow the master results there instead.

**Comment by brianjmurrell** [comment]
> If someone knows the proper commit pragma to use to skip the failing test in master I'm willing to try it again

You can use: `Skip-list-master: test_dfuse_daos_build_wt_pil4df:DAOS-16732`

There is debate about using that pragma but my opinion about it is that it's better to have the run passing while documenting that it only passed due to acknowledging (i.e. skipping) a known and unrelated failure and it should be included in the landing so that the landing also passes and the commit documents the known, unrelated failure.

**Review by brianjmurrell — APPROVED** [review]
LGTM, but it would be nicer if we could have CI showing it passing, and acknowledging the known and unrelated failures.

**Comment by soumagne** [comment]
Thanks, will rerun with that flag for master. The 2.6 failure is just one these random CI failures, I would expect it to pass.

**Review by frostedcmos — DISMISSED** [review]

**Comment by soumagne** [comment]
@brianjmurrell the commit pragma did not seem to work, did I miss something ? any idea ? Thanks.

**Comment by soumagne** [comment]
ah nvm I just see that I had missed an s at the end... 😮‍💨

**Comment by brianjmurrell** [comment]
> ah nvm I just see that I had missed an s at the end... 😮‍💨

Ahh.  That's my fault.  Kinda.  :grin:  I copy and pasted the test name from the ticket title in [DAOS-16732](https://daosio.atlassian.net/browse/DAOS-16732) which is also missing the trailing _s_.

**Comment by soumagne** [comment]
@brianjmurrell are you sure that's how we're supposed to skip those tests ? it still does not skip it (see https://github.com/daos-stack/libfabric/pull/77/commits/1abc98a6f2e65ea5e39cbc601fb1e1e79877b694)

**Review by gnailzenh — APPROVED** [review]

**Comment by phender** [comment]
Despite issues with being able to run all the stages in downstream testing in:
- master: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-libfabric-PR-77-master/25/
- release/2.6: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-libfabric-PR-77-release-2.6/24/
Testing passed in:
- master: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15401/1/
- release/2.6: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15441/1/

**Review by phender — APPROVED** [review]

**Pull request merged**
