### PR TITLE
DAOS-13767 libfabric: update to 1.18.1

### PR DESCRIPTION
**Pull request by soumagne**

### CODE REVIEW

**Comment by soumagne** [comment]
Update also addresses https://daosio.atlassian.net/browse/DAOS-13964

**Review by frostedcmos — APPROVED** [review]

**Comment by mchaarawi** [comment]
is there a DAOS PR that runs tests with this RPM?

**Comment by soumagne** [comment]
There will be once https://github.com/ofiwg/libfabric/pull/9164 is merged

**Comment by daltonbohning** [comment]
> is there a DAOS PR that runs tests with this RPM?

This master PR did, with my changes for fi_info -> hg_info:
https://github.com/daos-stack/daos/pull/12705

**Review by daltonbohning — APPROVED** [review]

**Pull request merged**
