### PR TITLE
DAOS-4943 sockets: Add messages for connect errors

### PR DESCRIPTION
**Pull request by liw**
Add error messages to sockets_provider.patch, so that libfabric will
report a more useful error when it fails to establish a connection.

Signed-off-by: Li Wei <wei.g.li@intel.com>

### CODE REVIEW

**Review by liuxuezhao — APPROVED** [review]
the code of this original patch already in ofi master, you may submitted another patch to ofi for what you added here.

**Comment by brianjmurrell** [comment]
> the code of this original patch already in ofi master, you may submitted another patch to ofi for what you added here.

So should we be using a newer ofi master commit than we are currently?

**Comment by liw** [comment]
> > the code of this original patch already in ofi master, you may submitted another patch to ofi for what you added here.
> 
> So should we be using a newer ofi master commit than we are currently?

I don't think I can make this call. @liuxuezhao, @frostedcmos?

**Comment by liw** [comment]
> `libfabric.spec`'s `Release:` needs to be incremented and a `%changelog` entry needs to be added if you intend to get this landed.

OK, I'll try update those.

**Comment by liw** [comment]
> the code of this original patch already in ofi master, you may submitted another patch to ofi for what you added here.

Not sure if they would agree with the extra SOCK_LOG_ERROR calls. You think we should try?

**Comment by liuxuezhao** [comment]
> > the code of this original patch already in ofi master, you may submitted another patch to ofi for what you added here.
> 
> Not sure if they would agree with the extra SOCK_LOG_ERROR calls. You think we should try?

I think using SOCK_LOG_DBG looks more appropriate for OFI upstream change.
But for ourself patch using  SOCK_LOG_ERROR seems fine.

**Comment by liuxuezhao** [comment]
> So should we be using a newer ofi master commit than we are currently?

may need to do some extra test if we upgrade ofi version to DAOS.

**Comment by liw** [comment]
> `libfabric.spec` changes look good. But one other thing I forgot to mention is that you need to refresh the files in the [`packaging/` subdir](https://github.com/daos-stack/libfabric/tree/1407f5e88bd58a83891841dbd769854d788ea074/packaging) with the [current content of the packaging repo](https://github.com/daos-stack/packaging). You don't want to just copy all of the files from that repo to `packaging/` in this PR, just update any of the existing files.
> 
> That should fix your CI failure.

Thanks, @brianjmurrell. I've updated the existing files in packaging with the corresponding files in the latest packaging.git. Not sure if the build will complete before the end of my day, so I clicked the re-review button anyway.

**Pull request merged**
